# Generated by Django 4.2.2 on 2023-07-04 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_scope_articles_scope_article_alter_scope_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='article',
        ),
        migrations.AddField(
            model_name='scope',
            name='articles',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='article_data', to='articles.article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(through='articles.Scope', to='articles.tag'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_data', to='articles.tag', verbose_name='Раздел'),
        ),
    ]
